import Head from "next/head";
import useFetchSession from "../../hooks/useFetchSession";
import Footer from "../Footer";
import LoadingScreen from "../LoadingScreen";
import MobileMenu from "../MobileMenu";
import SideBar from "../SideBar";
import Expense from "./Expense";
import { LOGGED_IN } from "../../utils";

export default function ExpensePage() {
  const { session, status } = useFetchSession({ options: LOGGED_IN });

  return (
    <>
      <Head>
        <title>Expense</title>
        <meta name="description" content="Generated by Masecodes" />
        <link rel="icon" href="/book_books_study_read_school_icon_209913.ico" />
      </Head>
      {status === "loading" ? (
        <LoadingScreen />
      ) : (
        <>
          {session && (
            <div className="screenContainer">
              <MobileMenu session={session} />
              <SideBar />
              <Expense session={session} />

              <div className="lg:hidden mt-10">
                <Footer />
              </div>
            </div>
          )}
        </>
      )}
    </>
  );
}
