import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import SideBar from "../components/ledger/SideBar";

function expense() {
  const { data: session } = useSession();
  const { status } = useSession({ required: true });
  return (
    <div>
      <Head>
        <title>Expense</title>
        <meta name="description" content="Generated by Masecodes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status === "loading" ? (
        <LoadingScreen />
      ) : (
        <>
          {session && (
            <div className="flex">
              <SideBar />
              <div className="flex-1">
                <h1 className="text-center">Expense</h1>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default expense;
