import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import SideBar from "../components/SideBar";
import LoadingScreen from "../components/LoadingScreen";
import { useEffect } from "react";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import { db } from "../firebase";
import MobileMenu from "../components/MobileMenu";
import Goals from "../components/goals/Goals";

function goals() {
  const { data: session, status } = useSession({ required: true });

  useEffect(() => {
    if (session) {
      setDoc(
        doc(db, "users", session.user.uid),
        {
          email: session.user.email,
          lastSeen: serverTimestamp(),
          photoURL: session.user.image,
          name: session.user.name,
        },
        { merge: true }
      );
    }
  }, [session][db]);
  return (
    <div className="pageContainer">
      <Head>
        <title>Goals</title>
        <meta name="description" content="Generated by Masecodes" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {status === "loading" ? (
        <LoadingScreen />
      ) : (
        <>
          {session && (
            <div className="screenContainer">
              <MobileMenu session={session} />
              <SideBar />
              <Goals session={session} />
            </div>
          )}
        </>
      )}
    </div>
  );
}

export default goals;
