import { signIn } from "next-auth/react";
import Head from "next/head";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-center">Ledger</h1>
      <button onClick={signIn}>Sign in</button>
    </div>
  );
}
