"use client"

import Head from "next/head"
import Ledger from "../components/ledger/Ledger"
import LoadingScreen from "../components/LoadingScreen"
import WelcomeScreen from "../components/WelcomeScreen"
import useFetchSession from "../hooks/useFetchSession"
import { LOGGED_OUT } from "../utils"

export default function Home() {
  const { session, status } = useFetchSession({ options: LOGGED_OUT })

  return (
    <div className="pageContainer">
      <Head>
        <title>LedgerMe</title>
        <meta name="description" content="Generated by Masecodes" />
        <link rel="icon" href="/book_books_study_read_school_icon_209913.ico" />
      </Head>
      <>{status === "loading" ? <LoadingScreen /> : <>{!session ? <WelcomeScreen /> : <Ledger session={session} />}</>}</>
    </div>
  )
}
